### ISSUE TITLE
Can we use margin-bottom or margin-right to add item spacing of auto layout instead of add empty div?

### ISSUE THREAD

**Issue by oney** [bernaferrari/FigmaToCode#29]
The code pointer is https://github.com/bernaferrari/FigmaToCode/blob/master/src/html/htmlMain.ts#L61
It's more a preference, but normally when we write html/css to add spacing, I believe we will use margin-bottom or margin-right rather than adding empty div.

**Comment by bernaferrari** [comment]
That's hard because there is no right way, css is terrible. The issue with setting margin-top and margin-bottom on each element is that it would probably get harder to understand, and there would be the issue where you can't reorder items by hand. When you see the empty divs you can just see what is going on.
